# Generated by Django 5.2.12 on 2026-05-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('notification_type', models.CharField(choices=[('drive_announce', 'Drive Announcement'), ('shortlist', 'Shortlist Notification'), ('interview_scheduled', 'Interview Scheduled'), ('course_started', 'Course Started'), ('general', 'General Announcement')], max_length=50)),
                ('target_role', models.CharField(choices=[('student', 'Student'), ('recruiter', 'Recruiter'), ('tpo', 'TPO'), ('all', 'All')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'student_notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
