# Generated by Django 5.2.12 on 2026-05-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('interview_scheduled', 'Interview Scheduled'), ('selected', 'Selected')], default='applied', max_length=30)),
                ('match_score', models.IntegerField(default=0, help_text='AI match score 0-100')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'applications',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('rounds_description', models.TextField(help_text='Description of interview rounds')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20)),
                ('questions_asked', models.TextField(blank=True, help_text='Questions asked in interview')),
                ('tips', models.TextField(blank=True, help_text='Tips for future candidates')),
                ('result', models.CharField(choices=[('selected', 'Selected'), ('rejected', 'Rejected')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'interview_experiences',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_type', models.CharField(choices=[('aptitude', 'Aptitude'), ('technical', 'Technical'), ('hr', 'HR'), ('group_discussion', 'Group Discussion')], max_length=30)),
                ('scheduled_date', models.DateTimeField()),
                ('location', models.CharField(blank=True, help_text='Online or physical location', max_length=200)),
                ('result', models.CharField(choices=[('pending', 'Pending'), ('pass', 'Pass'), ('fail', 'Fail')], default='pending', max_length=20)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'interview_schedules',
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='PlacementDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('package', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('eligibility_cgpa', models.FloatField(default=0.0)),
                ('required_skills', models.TextField(help_text='Comma-separated skills')),
                ('eligible_branches', models.CharField(help_text='Comma-separated branches', max_length=500)),
                ('drive_date', models.DateTimeField()),
                ('registration_deadline', models.DateTimeField()),
                ('total_positions', models.IntegerField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'placement_drives',
                'ordering': ['-drive_date'],
            },
        ),
    ]
