# Generated by Django 5.2.12 on 2026-05-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('aptitude', 'Aptitude'), ('technical', 'Technical'), ('soft_skills', 'Soft Skills'), ('other', 'Other')], max_length=100)),
                ('duration_hours', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_percentage', models.FloatField(default=0.0)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'enrollments',
            },
        ),
        migrations.CreateModel(
            name='MockTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('quant', 'Quantitative Aptitude'), ('verbal', 'Verbal Ability'), ('logical', 'Logical Reasoning'), ('technical', 'Technical'), ('coding', 'Coding')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('total_questions', models.IntegerField()),
                ('duration_minutes', models.IntegerField()),
                ('passing_score', models.IntegerField(default=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'mock_tests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20)),
                ('correct_answer', models.CharField(max_length=500)),
                ('explanation', models.TextField(blank=True)),
                ('marks', models.IntegerField(default=1)),
                ('order', models.IntegerField()),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['test', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.IntegerField()),
            ],
            options={
                'db_table': 'question_options',
                'ordering': ['question', 'order'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('time_taken_seconds', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'student_answers',
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('total_marks', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('weak_areas', models.TextField(blank=True, help_text='JSON data of weak areas')),
                ('time_taken_seconds', models.IntegerField()),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'test_attempts',
                'ordering': ['-completed_at'],
            },
        ),
    ]
